## Numpy 모듈
- 과학 기술 계산을 위한 라이브러리
- 행렬 / 배열 처리 미치 연산
- 난수 생성

In [1]:
import numpy as np

### 1차원(1D) 배열 구조

In [3]:
listD = [20, 10, 15, 8, 9, 10]
print(type(listD))
print(listD)                     # 리스트형

<class 'list'>
[20, 10, 15, 8, 9, 10]


In [5]:
np.array(listD)
print(type(np.array(listD)))
print(np.array(listD))            # 벡터형

<class 'numpy.ndarray'>
[20 10 15  8  9 10]


In [7]:
print(np.array(listD).shape)     # 배열의 차원을 튜플 구조로 표시

(6,)


In [10]:
# 1차원 데이터 관리
arr = np.array(listD)
# 데이터 출력
print(arr[0], arr[3])
# 데이터 수정
arr[1] = 22
print(arr)

20 8
[20 22 15  8  9 10]


In [19]:
list1 = [[10, 20, 30],[15, 25, 35]]
arr = np.array(list1)
# 정보 형태 확인
print(arr.shape)

# 차원 확인(ndim)
print(arr.ndim)

# 전체 데이터 갯수(size)
print(len(list1[0]) + len(list1[1]))
print(arr.size)

# 데이터 타입 확인(dtype)
print(arr.dtype)

# 원소의 크기(itemsize)
print(arr.itemsize)

# 원소와 하나의 행의 크기(strides)
print(arr.strides)

(2, 3)
2
6
6
int64
8
(24, 8)


### ndarray 생성
- 기본적으로 vectorization과 broadcasting을 지원
- list, tuple 등의 시퀀스 자료형으로 구성할 수 있으며 내부 요소의 자료형은 모두 동일한 타입으로만 가질 수 있다.
- 자료의 크기도 고정되어 있음

In [31]:
arr = np.array((1, 2, 3))
print(arr)
print(arr.dtype)
print(arr.shape)

[1 2 3]
int64
(3,)


In [33]:
arr = np.array(((1, 2, 3.), (1, 2, 3.)))
print(arr)
print(arr.dtype)
print(arr.shape)

[[1. 2. 3.]
 [1. 2. 3.]]
float64
(2, 3)


In [34]:
arr = np.array([[(1, 2, 3.), (10, 20, "30")],
               [(1, 33, 25), (15., 22.0, 35)],
                [(10, 3, 25), (15., 22.0, 35)]])
print(arr)
print(arr.dtype)
print(arr.shape)    # 1차원:(m, ) / 2차원:(m, n) / 3차원:(m, n, q)

[[['1' '2' '3.0']
  ['10' '20' '30']]

 [['1' '33' '25']
  ['15.0' '22.0' '35']]

 [['10' '3' '25']
  ['15.0' '22.0' '35']]]
<U32
(3, 2, 3)


In [35]:
arr = np.array((1, 2, 3), dtype="float64")
print(arr)
print(arr.dtype)
print(arr.shape)

[1. 2. 3.]
float64
(3,)


In [36]:
# 새로운 데이터를 받아와 순차적으로 array 만들기
arr = np.array([])

for i in range(3):
    arr = np.append(arr,[10, 20, 30])

print(arr)

[10. 20. 30. 10. 20. 30. 10. 20. 30.]


In [38]:
# 순차적인 배열 값 만들기
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
# reshape로 차원 조정하기
arr = np.arange(18).reshape(3, 6)  # reshape(3, 5)의 숫자의 곱은 array(15)의 숫자와 일치
print(arr, "\n")

arr1 = arr.reshape(2,9)            # (3, 6)의 구조를 (2, 9)로 변경
print(arr1, "\n")

arr1 = arr.reshape(2, -1)          # 행을 기준으로 열 원소를 자동으로 계산
print(arr1, "\n")

arr1 = arr.reshape(-1, 9)          # 원소의 갯수를 기준으로 행의 갯수 자동 계산
print(arr1, "\n")

arr1 = arr.reshape(-1)             # 1차원 구조로 변경
print(arr1, "\n")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]] 

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]] 

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17] 



### array 연산

In [49]:
# 배열 계산(합계)
print(arr)
print("전체 데이터 합계:", np.sum(arr))
print("열 기준 합계/axis=0:", np.sum(arr, axis=0))
print("행 기준 합계/axis=1:", np.sum(arr, axis=1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
전체 데이터 합계: 153
열 기준 합계/axis=0: [18 21 24 27 30 33]
행 기준 합계/axis=1: [15 51 87]


In [51]:
# array간 사칙연산
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# 더하기
print(arr1 + arr2)
# 빼기
print(arr1 - arr2)
# 곱하기
print(arr1 * arr2)
# 나누기
print(arr1 / arr2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [52]:
# array간 사칙연산
arr1 = np.array([1, 2, 3, 4]).reshape(2, -1)
arr2 = np.array([5, 6,])

# 더하기
print(arr1 + arr2)
# 빼기
print(arr1 - arr2)
# 곱하기
print(arr1 * arr2)
# 나누기
print(arr1 / arr2)

[[ 6  8]
 [ 8 10]]
[[-4 -4]
 [-2 -2]]
[[ 5 12]
 [15 24]]
[[0.2        0.33333333]
 [0.6        0.66666667]]


### 배열에 대한 인덱싱 / 합치기

In [55]:
arr = np.arange(0, 20, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
from numpy.lib.function_base import append
# 요소 인덱싱
print(arr[0])
print(arr[[0, 3, 5]])
print(arr[2:5])

0
[ 0  6 10]
[4 6 8]


In [62]:
# True / False로 구성된 boolean 배열을 기준 출력
print(arr >= 10)
print(arr[arr >= 10])

[False False False False False  True  True  True  True  True]
[10 12 14 16 18]


In [64]:
# 0이 아닌 값만 출력
arr[[3, -1]] = 0
print(arr)
print(np.nonzero(arr))

[ 0  2  4  0  8 10 12 14 16  0]
(array([1, 2, 4, 5, 6, 7, 8]),)


In [68]:
arr = arr.reshape(2, -1)
print(arr, "\n")
print(arr[0, 1:4])    # 1행 이면서 1 ~ 4 사이 열 값 출력
print(arr[:, 1:4])    # 모든 행에서 1 ~ 4 사이 열 값 출력

[[ 0  2  4  0  8]
 [10 12 14 16  0]] 

[2 4 0]
[[ 2  4  0]
 [12 14 16]]


In [77]:
# array 합치기

arr1 = np.arange(1, 5).reshape(2, -1)
arr2 = np.array([5, 6])

print(arr1.ndim, arr2.ndim)

print(arr1, "\n", arr2)
# print(np.concatenate((arr1, arr2), axis=0))

2 1
[[1 2]
 [3 4]] 
 [5 6]


In [81]:
# array 합치기

arr1 = np.arange(1, 5).reshape(2, -1)
arr2 = np.array([5, 6]).reshape(-1, 2)

print(arr1.ndim, arr2.ndim)

print(arr1, "\n", arr2)
print(np.concatenate((arr1, arr2), axis=0), "\n")
print(np.concatenate((arr1, arr2.T), axis=1), "\n")
print(np.concatenate((arr1, arr2.reshape(2, -1)), axis=1))

2 2
[[1 2]
 [3 4]] 
 [[5 6]]
[[1 2]
 [3 4]
 [5 6]] 

[[1 2 5]
 [3 4 6]] 

[[1 2 5]
 [3 4 6]]
